### ISSUE TITLE
wasm-coredump-encoder encoding vecs with fixed-length u32 instead of LEB128

### ISSUE THREAD

**Issue by itsrainy** [xtuc/wasm-coredump#2]
I ran into some differences while implementing coredump encoding in the wasm-tools repository. Specifically the encoder here seems to differ from the [spec in the tool-conventions repo](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md) in a couple ways:

[WebAssembly's vec definition](https://webassembly.github.io/spec/core/binary/conventions.html#binary-vec) has a u32 prefix for the length, and u32s should be encoded with [LEB128](https://webassembly.github.io/spec/core/binary/values.html#integers). The encoder here seems to deviate from that [when encoding the stack frames](https://github.com/xtuc/wasm-coredump/blob/main/lib/coredump-encoder/src/lib.rs#L38-L48).

I also noticed that there is a 0-value u32 getting added [here](https://github.com/xtuc/wasm-coredump/blob/main/lib/coredump-encoder/src/lib.rs#L40) after the length of the stack frames vec, which I don't think should be there.

**Comment by xtuc** [comment]
Thanks for the issue.

> [WebAssembly's vec definition](https://webassembly.github.io/spec/core/binary/conventions.html#binary-vec) has a u32 prefix for the length, and u32s should be encoded with [LEB128](https://webassembly.github.io/spec/core/binary/values.html#integers). The encoder here seems to deviate from that [when encoding the stack frames](https://github.com/xtuc/wasm-coredump/blob/main/lib/coredump-encoder/src/lib.rs#L38-L48).

You are right, the u32s should be encoded as LEB128. It's left over from my initial coredump encoder written by hand, was easier for me. We should fix it before the breaking change is too bad.

> I also noticed that there is a 0-value u32 getting added [here](https://github.com/xtuc/wasm-coredump/blob/main/lib/coredump-encoder/src/lib.rs#L40) after the length of the stack frames vec, which I don't think should be there.

That's a mistake. However in the `frame` definition:
```
frame       ::= 0x0 funcidx:u32 codeoffset:u32 locals:vec(value)
                stack:vec(value)
```

0x0 is used as a version, it should be written for each frame, not just at the begning.

Also out of curiosity, are you rewriting a coredump encoder in wasm-tools? Can't we reuse the one here?

**Comment by fitzgen** [comment]
> Also out of curiosity, are you rewriting a coredump encoder in wasm-tools? Can't we reuse the one here?

Yes we are adding support for generating core dumps to our existing `wasm-encoder` crate and intend to use this in Wasmtime. We already maintain an ecosystem of wasm parsers/encoders/etc in the Wasmtime project/the Bytecode Alliance and don't generally want to pull in other wasm-encoding libraries if we can help it.

In general, it is good to have multiple implementations of a standard, as it shakes out issues across implementations, such as those reported here, and ultimately makes all implementations better and the standard stronger because of it.

**Comment by xtuc** [comment]
I made a few spec complicancy changes, I still have to do the the u32 -> LEB128 change.

**Comment by xtuc** [comment]
Sorry for the delay, I have some free time on Thursday / Friday. I'm planning to do the u32 -> LEB128 change.

**Comment by xtuc** [comment]
This has been fixed and release as wasmgdb/wasm-coredump-encoder@0.1.14.
